@base_url = http://localhost:5098/api

# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST http://localhost:5098/api/funcionario/cadastrar
Content-Type: application/json

{
    "nome": "Matheus",
    "cpf" : "12345678912",
    "valorHora" : 10 

}

### Obtenção de todos os funcionários
http://localhost:5098/api/funcionario/listar

# FOLHA ############################################

### Criação de uma nova folha
POST http://localhost:5098/api/folha/cadastrar
Content-Type: application/json

{
    "valor": 50,
    "quantidade" : 1000,
    "mes" : 10,
    "ano" : 2023,
    "funcionarioId" : 16
}

### Obtenção de todas as folhas
GET http://localhost:5098/api/folha/listar

### Obtenção de uma folha
GET http://localhost:5098/api/folha/buscar/12345678912/10/2023